### ISSUE TITLE
Significant world loading slowdown, when used in a modpack

### ISSUE THREAD

**Issue by SplendidAlakey** [roland-a/StrategicEnchanting#1]
Without the mod it takes me just under 1min to load into a world, whereas with the mod it's at least 2 minutes longer. The slowdown specifically happens after all chunks have been generated, as seen by the chunkloading preview screen. And it also affects the `/reload` command.

Here's a [JVisualVM](https://visualvm.github.io/) profiler report, taken during the world loading. It took me just around 30sec to actually load the world, after which I had to wait for an additional 2min30sec before actually getting in: [removed]

Without Strategic Enchanting, I just takes me 30sec to load into the world. I can record a separate profiler session for it, if needed.

The latest.log doesn't show anything other than the fact, that it takes 3min between me clicking on the play button and actually joining the world.

Let me know if I can help any further.

**Comment by unaverage** [comment]
I'm not exactly sure if the most recent release completely fix that performance issue you're having. I couldn't replicate a development environment where my mod was causing a minute delay with world loading. Can you let me know how well the recent release is working for you?

**Comment by SplendidAlakey** [comment]
Completely fixed, thank you!
