### ISSUE TITLE
feedback/bug: can still pillar/bridge by building this way

### ISSUE THREAD

**Issue by bloodmasked** [roland-a/StrategicEnchanting#5]
![image](https://github.com/roland-a/UnaverageTweaks/assets/6406832/c7200ac7-f055-4b30-933e-3aea1fb65b14)

green->red->blue

then green starting on red again

**Comment by roland-a** [comment]
I did not mean to close this issue right away.
But I did just fix it.
The fix will show up in the next upcoming version.

**Comment by roland-a** [comment]
Its fixed in V4.
