### ISSUE TITLE
Crash - Feature placement

### ISSUE THREAD

**Issue by slammaja** [roland-a/StrategicEnchanting#7]
Hello, from time to time I am getting this crash on server and I believe this happens in SP as well.
Game crashes randomly while exploring around a world and everytime it is related to enchantments from MCDW or MCDA.
[crash-2024-06-02_10.38.16-server.txt](https://github.com/user-attachments/files/15524697/crash-2024-06-02_10.38.16-server.txt)

**Comment by roland-a** [comment]
Should be fixed now
